import { convertToExcalidrawElements } from "@excalidraw/excalidraw";

const elements = convertToExcalidrawElements([
  // Node A
  {
    type: "rectangle",
    id: "node-a",
    x: 100,
    y: 100,
    width: 60,
    height: 40,
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "#d3f8e2",
    fillStyle: "solid",
    strokeWidth: 1,
    roughness: 1,
    opacity: 100,
    groupIds: [],
    boundElements: [],
    seed: 1,
    version: 1,
    versionNonce: 111,
    // isDeleted: false,
    locked: false,
  },
  {
    type: "text",
    id: "text-a",
    x: 115,
    y: 112,
    width: 30,
    height: 20,
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1,
    roughness: 0,
    opacity: 100,
    groupIds: [],
    boundElements: [],
    seed: 2,
    version: 1,
    versionNonce: 112,
    text: "A",
    fontSize: 20,
    fontFamily: 1,
    textAlign: "center",
    verticalAlign: "middle",
    // baseline: 18,
    isDeleted: false,
    locked: false,
  },

  // Arrow A → B
  {
    type: "arrow",
    id: "arrow-a-b",
    x: 160,
    y: 120,
    width: 40,
    height: 0,
    points: [[0, 0], [40, 0]],
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 2,
    roughness: 1,
    opacity: 100,
    groupIds: [],
    boundElements: [],
    seed: 3,
    version: 1,
    versionNonce: 113,
    isDeleted: false,
    locked: false,
  },

  // Node B
  {
    type: "rectangle",
    id: "node-b",
    x: 200,
    y: 100,
    width: 60,
    height: 40,
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "#fce38a",
    fillStyle: "solid",
    strokeWidth: 1,
    roughness: 1,
    opacity: 100,
    groupIds: [],
    boundElements: [],
    seed: 4,
    version: 1,
    versionNonce: 114,
    // isDeleted: false,
    locked: false,
  },
  {
    type: "text",
    id: "text-b",
    x: 215,
    y: 112,
    width: 30,
    height: 20,
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1,
    roughness: 0,
    opacity: 100,
    groupIds: [],
    boundElements: [],
    seed: 5,
    version: 1,
    versionNonce: 115,
    text: "B",
    fontSize: 20,
    fontFamily: 1,
    textAlign: "center",
    verticalAlign: "middle",
    // baseline: 18,
    isDeleted: false,
    locked: false,
  },

  // Arrow B → C
  {
    type: "arrow",
    id: "arrow-b-c",
    x: 260,
    y: 120,
    width: 40,
    height: 0,
    points: [[0, 0], [40, 0]],
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 2,
    roughness: 1,
    opacity: 100,
    groupIds: [],
    boundElements: [],
    seed: 6,
    version: 1,
    versionNonce: 116,
    isDeleted: false,
    locked: false,
  },

  // Node C
  {
    type: "rectangle",
    id: "node-c",
    x: 300,
    y: 100,
    width: 60,
    height: 40,
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "#ffaaa5",
    fillStyle: "solid",
    strokeWidth: 1,
    roughness: 1,
    opacity: 100,
    groupIds: [],
    boundElements: [],
    seed: 7,
    version: 1,
    versionNonce: 117,
    // isDeleted: false,
    locked: false,
  },
  {
    type: "text",
    id: "text-c",
    x: 315,
    y: 112,
    width: 30,
    height: 20,
    angle: 0,
    strokeColor: "#000000",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1,
    roughness: 0,
    opacity: 100,
    groupIds: [],
    boundElements: [],
    seed: 8,
    version: 1,
    versionNonce: 118,
    text: "C",
    fontSize: 20,
    fontFamily: 1,
    textAlign: "center",
    verticalAlign: "middle",
    // baseline: 18,
    isDeleted: false,
    locked: false,
  },
]);

export default elements